version: '3.9'

services:
  server:
    build: .
    ports:
      - "5000:5000"
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: 'refuge'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: